# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f349b0e043b1380ee121b5c0571ca04e5e936067e248cf1821b32e3c0e9c4673cf676f639b37bbb36edcc62ccc2b49db219f0904703f0d5cb4bfa65e44f8fda3

test:
  secret_key_base: 4d0927845f09703769cfb22ded051f52cb1c39ccc1f762f0f8d8baab12e444257d22222ad6465de8e0df130f5b6d9c92c604a1960b85fe56d184b59229f488c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
